In [1]:
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('inferences.csv')
df = df.iloc[:,1:]

In [2]:
df

     SEED  NOISE           DATASET      MODEL     ERROR
0    1234    0.0  SIMULATION_00_03     FF_200  0.000428
1    1234    0.0  SIMULATION_00_03     FF_400  0.000366
2    1234    0.0  SIMULATION_00_03     FF_800  0.000368
3    1234    0.0  SIMULATION_00_03    FF_1600  0.000107
4    1234    0.0  SIMULATION_00_03  PIDNN_200  0.000173
..    ...    ...               ...        ...       ...
310  4132    0.1  SIMULATION_00_40     FF_800  0.002054
311  4132    0.1  SIMULATION_00_40    FF_1600  0.001731
312  4132    0.1  SIMULATION_00_40  PIDNN_200  0.000749
313  4132    0.1  SIMULATION_00_40  PIDNN_400  0.000916
314  4132    0.1  SIMULATION_00_40  PIDNN_800  0.000324

[315 rows x 5 columns]

In [3]:
noises = list(set(df['NOISE']))
datasets = list(set(df['DATASET']))
models = list(set(df['MODEL']))

In [4]:
MEAN_ERR = df.groupby(['NOISE','DATASET','MODEL']).mean()['ERROR'].tolist()
STD_ERR = df.groupby(['NOISE','DATASET','MODEL']).std()['ERROR'].tolist()

In [5]:
df = df[['NOISE','DATASET','MODEL']].drop_duplicates()
df['MEAN_ERR'] = MEAN_ERR
df['STD_ERR'] = STD_ERR
df

     NOISE           DATASET      MODEL  MEAN_ERR   STD_ERR
0      0.0  SIMULATION_00_03     FF_200  0.000077  0.000038
1      0.0  SIMULATION_00_03     FF_400  0.003097  0.003970
2      0.0  SIMULATION_00_03     FF_800  0.000288  0.000073
3      0.0  SIMULATION_00_03    FF_1600  0.000247  0.000132
4      0.0  SIMULATION_00_03  PIDNN_200  0.000072  0.000087
..     ...               ...        ...       ...       ...
100    0.1  SIMULATION_00_40     FF_800  0.000577  0.000074
101    0.1  SIMULATION_00_40    FF_1600  0.000271  0.000118
102    0.1  SIMULATION_00_40  PIDNN_200  0.000240  0.000080
103    0.1  SIMULATION_00_40  PIDNN_400  0.000101  0.000039
104    0.1  SIMULATION_00_40  PIDNN_800  0.000039  0.000021

[105 rows x 5 columns]

In [7]:
df.to_csv('cleaned_inferences.csv', index=False)